# Generated by Django 5.0.1 on 2025-11-20 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(max_length=255)),
                ('child_pool', models.CharField(max_length=255)),
                ('allocated_gb', models.FloatField(default=0)),
                ('utilized_gb', models.FloatField(default=0)),
                ('left_gb', models.FloatField(default=0)),
                ('avg_utilization', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-utilized_gb'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=255)),
                ('volume_size_gb', models.FloatField()),
                ('written_by_host_percent', models.FloatField()),
                ('child_pool', models.CharField(max_length=255)),
                ('utilized_gb', models.FloatField()),
                ('left_gb', models.FloatField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='analytics.tenant')),
            ],
            options={
                'ordering': ['-utilized_gb'],
            },
        ),
    ]
