# Generated by Django 5.0.1 on 2025-11-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='tenant',
        ),
        migrations.CreateModel(
            name='StorageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=255)),
                ('pool', models.CharField(max_length=255)),
                ('child_pool', models.CharField(max_length=255)),
                ('volume_size_gb', models.FloatField()),
                ('utilized_gb', models.FloatField()),
                ('left_gb', models.FloatField()),
            ],
            options={
                'db_table': 'storage_data',
                'indexes': [models.Index(fields=['pool'], name='storage_dat_pool_4317fa_idx'), models.Index(fields=['pool', 'child_pool'], name='storage_dat_pool_46f37c_idx'), models.Index(fields=['volume'], name='storage_dat_volume_baeb31_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
